name: Ingest YouTube Playlist

on:
  workflow_dispatch:
    inputs:
      playlist_id:
        description: "Youtube video playlist id"
        required: true
      port_context:
        description: "The port context"
        type: string
        required: true

jobs:
  ingest-data:
    runs-on: ubuntu-latest
    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      PLAYLIST_ID: ${{ github.event.inputs.playlist_id }}
      PORT_CONTEXT: ${{ inputs.port_context }}
      PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
      PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
    steps:
      - name: Process Playlist and Videos
        run: |
          # Get Port token at the start
          echo "Getting Port token..."
          TOKEN_RESPONSE=$(curl -s -X POST "https://api.getport.io/v1/auth/access_token" \
            -H "Content-Type: application/json" \
            -d "{
              \"clientId\": \"$PORT_CLIENT_ID\",
              \"clientSecret\": \"$PORT_CLIENT_SECRET\"
            }")
          
          PORT_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.accessToken')
          if [ -z "$PORT_TOKEN" ] || [ "$PORT_TOKEN" = "null" ]; then
            echo "Failed to get access token"
            echo "Response: $TOKEN_RESPONSE"
            exit 1
          fi

          # Update Port action status
          RUN_ID=$(echo "$PORT_CONTEXT" | jq -r --raw-input 'fromjson | .runId')
          
          curl -X PATCH "https://api.getport.io/v1/actions/runs/$RUN_ID" \
            -H "Authorization: Bearer $PORT_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"status":"RUNNING","message":"Starting playlist ingestion"}'

          # Function to create Port entity
          create_port_entity() {
            local BLUEPRINT=$1
            local PAYLOAD=$2
            curl -s -X POST "https://api.getport.io/v1/blueprints/${BLUEPRINT}/entities" \
              -H "Authorization: Bearer ${PORT_TOKEN}" \
              -H "Content-Type: application/json" \
              -d "$PAYLOAD"
          }

          # Fetch playlist data
          echo "Fetching playlist data"
          PLAYLIST_DATA=$(curl -s "https://youtube.googleapis.com/youtube/v3/playlists?part=snippet,contentDetails&id=${PLAYLIST_ID}&key=${YOUTUBE_API_KEY}")
          
          if [ "$(echo $PLAYLIST_DATA | jq '.items | length')" -eq 0 ]; then
            curl -X PATCH "https://api.getport.io/v1/actions/runs/$RUN_ID" \
              -H "Authorization: Bearer $PORT_TOKEN" \
              -H "Content-Type: application/json" \
              -d '{"status":"FAILED","message":"Playlist not found"}'
            exit 1
          fi

          # Process playlist info
          TITLE=$(echo $PLAYLIST_DATA | jq -r '.items[0].snippet.title')
          DESC=$(echo $PLAYLIST_DATA | jq -r '.items[0].snippet.description')
          THUMB=$(echo $PLAYLIST_DATA | jq -r '.items[0].snippet.thumbnails.default.url')
          COUNT=$(echo $PLAYLIST_DATA | jq -r '.items[0].contentDetails.itemCount')

          # Create playlist entity
          PLAYLIST_PAYLOAD=$(jq -n \
            --arg id "$PLAYLIST_ID" \
            --arg title "$TITLE" \
            --arg desc "$DESC" \
            --arg thumb "$THUMB" \
            --arg count "$COUNT" \
            '{
              identifier: $id,
              title: $title,
              properties: {
                title: $title,
                description: $desc,
                thumbnail_url: $thumb,
                video_count: ($count|tonumber)
              }
            }')

          echo "Creating playlist entity"
          create_port_entity "playlist" "$PLAYLIST_PAYLOAD"

          # Initialize counters
          VIDEOS_PROCESSED=0
          VIDEOS_FAILED=0

          # Process videos function
          process_videos() {
            local PAGE_TOKEN=$1
            local API_URL="https://youtube.googleapis.com/youtube/v3/playlistItems?part=contentDetails&maxResults=50&playlistId=${PLAYLIST_ID}&key=${YOUTUBE_API_KEY}"
            if [ -n "${PAGE_TOKEN}" ]; then
              API_URL="${API_URL}&pageToken=${PAGE_TOKEN}"
            fi

            local ITEMS_RESPONSE=$(curl -s "${API_URL}")
            echo $ITEMS_RESPONSE | jq -r '.items[].contentDetails.videoId' | while read -r VIDEO_ID; do
              echo "Processing video: ${VIDEO_ID}"
              
              VIDEO_DATA=$(curl -s "https://youtube.googleapis.com/youtube/v3/videos?part=snippet,contentDetails,statistics&id=${VIDEO_ID}&key=${YOUTUBE_API_KEY}")
              
              if [ "$(echo $VIDEO_DATA | jq '.items | length')" -gt 0 ]; then
                local V_TITLE=$(echo $VIDEO_DATA | jq -r '.items[0].snippet.title')
                local V_DESC=$(echo $VIDEO_DATA | jq -r '.items[0].snippet.description')
                local V_THUMB=$(echo $VIDEO_DATA | jq -r '.items[0].snippet.thumbnails.default.url')
                local V_DURATION=$(echo $VIDEO_DATA | jq -r '.items[0].contentDetails.duration')
                local V_VIEWS=$(echo $VIDEO_DATA | jq -r '.items[0].statistics.viewCount // "0"')
                local V_LIKES=$(echo $VIDEO_DATA | jq -r '.items[0].statistics.likeCount // "0"')
                local V_COMMENTS=$(echo $VIDEO_DATA | jq -r '.items[0].statistics.commentCount // "0"')

                local VIDEO_PAYLOAD=$(jq -n \
                  --arg id "$VIDEO_ID" \
                  --arg title "$V_TITLE" \
                  --arg desc "$V_DESC" \
                  --arg thumb "$V_THUMB" \
                  --arg duration "$V_DURATION" \
                  --arg views "$V_VIEWS" \
                  --arg likes "$V_LIKES" \
                  --arg comments "$V_COMMENTS" \
                  --arg playlist_id "$PLAYLIST_ID" \
                  '{
                    identifier: $id,
                    title: $title,
                    properties: {
                      title: $title,
                      description: $desc,
                      thumbnail_url: $thumb,
                      duration: $duration,
                      view_count: ($views|tonumber),
                      like_count: ($likes|tonumber),
                      comment_count: ($comments|tonumber)
                    },
                    relations: {
                      belongs_to: $playlist_id
                    }
                  }')

                if create_port_entity "video" "$VIDEO_PAYLOAD"; then
                  ((VIDEOS_PROCESSED++))
                else
                  ((VIDEOS_FAILED++))
                fi

                if [ $((VIDEOS_PROCESSED % 5)) -eq 0 ]; then
                  curl -X PATCH "https://api.getport.io/v1/actions/runs/$RUN_ID" \
                    -H "Authorization: Bearer $PORT_TOKEN" \
                    -H "Content-Type: application/json" \
                    -d "{\"status\":\"RUNNING\",\"message\":\"Processed ${VIDEOS_PROCESSED} videos\"}"
                fi

                sleep 1
              else
                ((VIDEOS_FAILED++))
              fi
            done

            local NEXT_PAGE=$(echo $ITEMS_RESPONSE | jq -r '.nextPageToken')
            if [ "${NEXT_PAGE}" != "null" ]; then
              process_videos "${NEXT_PAGE}"
            fi
          }

          echo "Starting video processing"
          process_videos ""

          # Update final status
          curl -X PATCH "https://api.getport.io/v1/actions/runs/$RUN_ID" \
            -H "Authorization: Bearer $PORT_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"status\":\"SUCCESS\",\"message\":\"Completed: ${VIDEOS_PROCESSED} videos processed, ${VIDEOS_FAILED} failed\"}"

      - name: Report Failure
        if: failure()
        env:
          PORT_CONTEXT: ${{ inputs.port_context }}
        run: |
          # Get fresh token for failure reporting
          TOKEN_RESPONSE=$(curl -s -X POST "https://api.getport.io/v1/auth/access_token" \
            -H "Content-Type: application/json" \
            -d "{
              \"clientId\": \"${{ secrets.PORT_CLIENT_ID }}\",
              \"clientSecret\": \"${{ secrets.PORT_CLIENT_SECRET }}\"
            }")
          
          PORT_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.accessToken')
          RUN_ID=$(echo "$PORT_CONTEXT" | jq -r --raw-input 'fromjson | .runId')
          
          curl -X PATCH "https://api.getport.io/v1/actions/runs/$RUN_ID" \
            -H "Authorization: Bearer $PORT_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"status":"FAILED","message":"Workflow failed to complete"}'
