name: Ingest YouTube Playlist

on:
  workflow_dispatch:
    inputs:
      playlist_id:
        description: "Youtube video playlist id"
        required: true
      port_context:
        description: "The port context"
        required: true

jobs:
  authenticate:
    runs-on: ubuntu-latest
    outputs:
      port_token: ${{ steps.get_token.outputs.token }}
    steps:
      - name: Get Port Token
        id: get_token
        run: |
          if [ -n "${{ secrets.PORT_CLIENT_ID }}" ] && [ -n "${{ secrets.PORT_CLIENT_SECRET }}" ]; then
            TOKEN=$(curl -X POST "https://api.getport.io/v1/auth/access_token" \
              -H "Content-Type: application/json" \
              -d '{
                "clientId": "${{ secrets.PORT_CLIENT_ID }}",
                "clientSecret": "${{ secrets.PORT_CLIENT_SECRET }}"
              }' | jq -r '.accessToken')
          else
            TOKEN="${{ secrets.PORT_API_KEY }}"
          fi
          echo "token=${TOKEN}" >> "$GITHUB_OUTPUT"

  fetch-playlist:
    needs: authenticate
    runs-on: ubuntu-latest
    outputs:
      playlist_data: ${{ steps.get_playlist.outputs.data }}
    steps:
      - name: Get Playlist Info
        id: get_playlist
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          PLAYLIST_ID: ${{ github.event.inputs.playlist_id }}
        run: |
          PLAYLIST_DATA=$(curl -s "https://youtube.googleapis.com/youtube/v3/playlists?part=snippet,contentDetails&id=${PLAYLIST_ID}&key=${YOUTUBE_API_KEY}")
          echo "data=${PLAYLIST_DATA}" >> "$GITHUB_OUTPUT"

      - name: Create/Update Playlist Entity
        env:
          PORT_TOKEN: ${{ needs.authenticate.outputs.port_token }}
          PLAYLIST_DATA: ${{ steps.get_playlist.outputs.data }}
        run: |
          TITLE=$(echo $PLAYLIST_DATA | jq -r '.items[0].snippet.title')
          DESC=$(echo $PLAYLIST_DATA | jq -r '.items[0].snippet.description')
          THUMB=$(echo $PLAYLIST_DATA | jq -r '.items[0].snippet.thumbnails.default.url')
          COUNT=$(echo $PLAYLIST_DATA | jq -r '.items[0].contentDetails.itemCount')
          
          curl -X POST "https://api.getport.io/v1/blueprints/playlist/entities" \
            -H "Authorization: Bearer ${PORT_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{
              "identifier": "'${PLAYLIST_ID}'",
              "properties": {
                "title": "'${TITLE}'",
                "description": "'${DESC}'",
                "thumbnail_url": "'${THUMB}'",
                "video_count": '${COUNT}'
              }
            }'

  fetch-videos:
    needs: [authenticate, fetch-playlist]
    runs-on: ubuntu-latest
    steps:
      - name: Get Videos
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          PLAYLIST_ID: ${{ github.event.inputs.playlist_id }}
          PORT_TOKEN: ${{ needs.authenticate.outputs.port_token }}
        run: |
          process_video() {
            VIDEO_ID=$1
            VIDEO_DATA=$(curl -s "https://youtube.googleapis.com/youtube/v3/videos?part=snippet,contentDetails,statistics&id=${VIDEO_ID}&key=${YOUTUBE_API_KEY}")
            
            TITLE=$(echo $VIDEO_DATA | jq -r '.items[0].snippet.title')
            DESC=$(echo $VIDEO_DATA | jq -r '.items[0].snippet.description')
            THUMB=$(echo $VIDEO_DATA | jq -r '.items[0].snippet.thumbnails.default.url')
            DURATION=$(echo $VIDEO_DATA | jq -r '.items[0].contentDetails.duration')
            VIEWS=$(echo $VIDEO_DATA | jq -r '.items[0].statistics.viewCount')
            LIKES=$(echo $VIDEO_DATA | jq -r '.items[0].statistics.likeCount')
            COMMENTS=$(echo $VIDEO_DATA | jq -r '.items[0].statistics.commentCount')
            
            curl -X POST "https://api.getport.io/v1/blueprints/video/entities" \
              -H "Authorization: Bearer ${PORT_TOKEN}" \
              -H "Content-Type: application/json" \
              -d '{
                "identifier": "'${VIDEO_ID}'",
                "properties": {
                  "title": "'${TITLE}'",
                  "description": "'${DESC}'",
                  "thumbnail_url": "'${THUMB}'",
                  "duration": "'${DURATION}'",
                  "view_count": '${VIEWS}',
                  "like_count": '${LIKES}',
                  "comment_count": '${COMMENTS}'
                },
                "relations": {
                  "belongs_to": "'${PLAYLIST_ID}'"
                }
              }'
          }
          
          PAGE_TOKEN=""
          while true; do
            ENDPOINT="https://youtube.googleapis.com/youtube/v3/playlistItems?part=contentDetails&maxResults=50&playlistId=${PLAYLIST_ID}&key=${YOUTUBE_API_KEY}"
            if [ -n "$PAGE_TOKEN" ]; then
              ENDPOINT="${ENDPOINT}&pageToken=${PAGE_TOKEN}"
            fi
            
            RESPONSE=$(curl -s "$ENDPOINT")
            echo $RESPONSE | jq -r '.items[].contentDetails.videoId' | while read VIDEO_ID; do
              process_video "$VIDEO_ID"
            done
            
            PAGE_TOKEN=$(echo $RESPONSE | jq -r '.nextPageToken')
            if [ "$PAGE_TOKEN" = "null" ]; then
              break
            fi
          done
